### ISSUE TITLE
🗄️ Development 📌

### ISSUE THREAD

**Issue by EnzoHB** [EnzoHB/Number-Analyzer#1]
# ToDo List
**Everything I plan to do in the future.**

- [ ] **Features :**

  - [ ]  **Add Dinamic HTML pages with information about Numbers;**
  - [ ] **Add Math related things like Rule of Three, Equations, etcetera;**
  - [ ] **Everything I could possibly find on the Internet;** 🤖
  - **Content Source Probably : [Wikipedia, ](https://en.wikipedia.org/wiki/Main_Page)[Todamateria, ](https://www.todamateria.com.br/matematica/) [3Blue1Brown](https://www.youtube.com/c/3blue1brown/videos);**
- [ ] **Design :**

  - [ ] **Design a new clean and easy to understand UI;**
  - [ ] **Rewrite HTML in a semantic way;**
  - [ ] **Implement the UI;**
- [ ] **JavaScript :**

  - [ ] **For every Mathematical Procedures I find, I'll create my own version based on what I learned and use it.**
  - [ ] **Turn this into an Extension allowing a quick acces to all of those methods.**
  - [ ] **Putting everything together and Boom 💥! We've got a Website.** 

## My Philosophy

- __Fuc* all ads;__ :cursing_face:
- **Support me who wants;** :hugs:
- **A Platform filled with knowledge for free;**
___

**Something related with Programming would not be a bad ideia... :thinking:**
